version: "3"
services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:latest
    ports:
      - 10005:80
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
    environment:
      JWT_SECRET: aZ7nLXtCpmza9LhveXqxdbVQX7li7tD4
      MINIO_ACCESS_KEY: w7LG4jsVRcKedbs0P5Fi8z946eyaZbzm
      MINIO_SECRET_KEY: 1HxEpj2Kf6XXiCxKRyFYWDinIWAP2oMA
      REDIS_PASSWORD: VdZXYkEgqFdfolUR8rvIdk20Tl4CsynX
      INTERNAL_API_KEY: ZDIv7RTsO0vW0WO2K5FZFuHqIjxPb4s8
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: TJ0UXwtn7Y5DJaXYBNuoMnRJHjTbU2n4
      PLUGINS_DIR: /plugins
      BB_ADMIN_USER_EMAIL: admin@admin.com
      BB_ADMIN_USER_PASSWORD: admin
    volumes:
      - budibase_data:/data
      - /home/parallels/budibasePluginDev/budibase-recaptcha:/plugins
volumes:
  budibase_data:
    driver: local
